#### 矢量数据编辑（属性表编辑）与可视化

vector reading

In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt

In [3]:
path_data = 'data/section-3/kunming_district_gdf.gpkg'

In [4]:
kunming_gdf = gpd.read_file(path_data)

In [5]:
kunming_gdf.head(2)
print(list(kunming_gdf['dt_name']))

['五华区', '盘龙区', '官渡区', '西山区', '东川区', '呈贡区', '晋宁区', '富民县', '宜良县', '石林彝族自治县', '嵩明县', '禄劝彝族苗族自治县', '寻甸回族彝族自治县', '安宁市']

In [6]:
### 修改属性表
dt_name_new = ['wuhua', 'panlong', 'guandu', 'xishan', 'dongchuan', \
                'chenggong', 'jinning', 'fumin', 'yiliang', 'shilin', \
                  'sonming', 'luquan', 'xundian', 'anning']
kunming_gdf['dt_name'] = dt_name_new
kunming_gdf.head(2)

,dt_adcode,dt_name,ct_adcode,ct_name,pr_adcode,pr_name,cn_adcode,cn_name,geometry
0,530102,wuhua,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((102.71331 25.13652, 102.71547 ..."
1,530103,panlong,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((102.71668 25.04473, 102.71663 ..."

In [ ]:
## 计算面积
area_district = kunming_gdf.area
# print(area_district)

C:\Users\HP\AppData\Local\Temp\ipykernel_25184\2692040395.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  area_district = kunming_gdf.area

In [9]:
### 坐标系转换，后续会细讲
kunming_utm48_gdf = kunming_gdf.to_crs(32648)
# kunming_utm48_gdf.crs

In [62]:
area = kunming_utm48_gdf.area/1000000
# print(area)
kunming_utm48_gdf['area(km2)'] = area
kunming_utm48_gdf.head(2)

,dt_adcode,dt_name,ct_adcode,ct_name,pr_adcode,pr_name,cn_adcode,cn_name,geometry,area(km2)
0,530102,wuhua,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269466.597 2782018.804, 269686...",388.681330
1,530103,panlong,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269635.126 2771844.039, 269631...",864.295297

In [63]:
kunming_utm48_gdf.centroid
kunming_utm48_gdf['centroid'] = kunming_utm48_gdf.centroid
kunming_utm48_gdf.head(2)

,dt_adcode,dt_name,ct_adcode,ct_name,pr_adcode,pr_name,cn_adcode,cn_name,geometry,area(km2),centroid
0,530102,wuhua,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269466.597 2782018.804, 269686...",388.681330,POINT (264056.82 2787983.365)
1,530103,panlong,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269635.126 2771844.039, 269631...",864.295297,POINT (280956.817 2796083.348)

可视化

In [ ]:
## 可视化
ax = kunming_utm48_gdf.plot(legend=True, figsize=(6,6))
# ax = kunming_utm48_gdf.plot('area(km2)', legend=True, figsize=(6,6))
# ax.set_xticks([200000, 300000]);

In [ ]:
ax = kunming_utm48_gdf.plot("area(km2)", legend=True)
ax = kunming_utm48_gdf['centroid'].plot(color='red', ax=ax)

In [66]:
### 删除字段
kunming_utm48_gdf_ = kunming_utm48_gdf.drop('centroid', axis=1)
kunming_utm48_gdf_.head(2)

,dt_adcode,dt_name,ct_adcode,ct_name,pr_adcode,pr_name,cn_adcode,cn_name,geometry,area(km2)
0,530102,wuhua,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269466.597 2782018.804, 269686...",388.681330
1,530103,panlong,530100,昆明市,530000,云南省,100000,中华人民共和国,"MULTIPOLYGON (((269635.126 2771844.039, 269631...",864.295297

#### 利用geopandas创建矢量文件
创建同学信息矢量数据，包含同学家乡所在地位置几何信息，以及学生姓名、性别属性信息

In [67]:
from shapely.geometry import Point  ## 第六章节细讲

student_attr = {'name': ['zhang3', 'li4', 'wang5'], 
                'gender': ['male', 'female', 'male']}
student_loc = [Point(102.9, 25.64), Point(102.5, 25.86),  Point(102.6, 24.63)]
student_gpd = gpd.GeoDataFrame(data=student_attr,  
                               geometry=student_loc, 
                               crs='EPSG:4326')
student_gpd.head()
# student_gpd.plot()

     name  gender             geometry
0  zhang3    male  POINT (102.9 25.64)
1     li4  female  POINT (102.5 25.86)
2   wang5    male  POINT (102.6 24.63)

In [ ]:
ax = kunming_gdf.plot('dt_name', 
                      edgecolor='black', 
                      alpha=0.4)
student_gpd.plot(ax=ax, color='red')

将选课同学家乡信息csv表格写出为gpkg矢量数据

In [13]:
import pandas as pd
path_stud = '课程考核记录/2026春/students_hometown_2026.csv'
stud_pd = pd.read_csv(path_stud)
stud_pd.head(2)

    姓名 性别 家乡所在省 家乡所在市    家乡经度   家乡纬度
0  杨茗涵  女   云南省   昆明市  102.76  25.04
1  曾紫芯  女   湖南省   湘潭市  112.94  27.83

In [76]:
## 
stud_loc = []
lon_lat_zip = zip(stud_pd['家乡经度'].values, stud_pd['家乡纬度'].values)
for lon, lat in lon_lat_zip:
    # print((lon,lat))
    loc = Point(lon,lat)
    stud_loc.append(loc)

stud_gdf = gpd.GeoDataFrame(data=stud_pd,  
                            geometry=stud_loc, 
                            crs='EPSG:4326')
stud_gdf.head(2)

    姓名 性别 家乡所在省 家乡所在市    家乡经度   家乡纬度              geometry
0  杨茗涵  女   云南省   昆明市  102.76  25.04  POINT (102.76 25.04)
1  曾紫芯  女   湖南省   湘潭市  112.94  27.83  POINT (112.94 27.83)

#### 矢量数据写出

In [77]:
## 数据写出
path_out = 'data/data-section-3/kunming_district_gpd_2.gpkg'
path_student = 'data/section-3/students_hometown_2026.gpkg'
# gpd_utm48.to_file(path_out)
stud_gdf.to_file(path_student)